# Generated by Django 6.0.4 on 2026-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
