# Generated by Django 6.0.4 on 2026-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_user_fcm_token_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
