# Generated by Django 6.0.4 on 2026-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_customuser_fcm_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsearchhistory',
            options={},
        ),
    ]
